 <span class="boldtext">1. How do I install eStore onto my wordpress blog? </span> 
<div class="indent"> 
  <p>There are several files included in the ZIP folder. These include wordpress theme files, plugin files, and photoshop files. To installed your wordpress theme you will first need to upload the theme/plugin files via FTP to your server. </p> 
  <p>First you are going to upload the theme folder. Inside the ZIP folder you downloaded you will see a folder named &quot;theme.&quot; Within it is a folder named &quot;eStore.&quot; Via ftp, upload the &quot;eStore&quot; folder to your Wordpress themes directory. Depending on where you installed Wordpress on your server, the wp themes folder will be located in a path similar to: /public_html/blog/wp-content/themes. </p> 
  <p>Next you need to select eStore and make it your default theme. Click on the design link, and under the themes tab locate eStore from the selection of themes and activate it. Your blog should now be updated with your new theme. </p> 
<p>Finally, once the theme has been activated, you should navigate to the Appearances > eStore Theme Options page. Here you can adjust settings pertaining to theme's display. Once you have adjusted whatever settings you would like to change click the "save" button. You must click the "save" button for the options to be saved to the database. Even if you did not change anything you should click the save button once before using the theme to insure that the database has been written correctly.</p> 
</div> 
<span class="boldtext">2. How do I add the thumbnails to my posts? </span> 
<div class="indent"> 
  <p>When you write a post, you will see list of options below the text editor labeled ET Settings. Within this box you will see four fields where you can input your thumbnail images. You can have up to four images displayed with each post, the first of which will be used as your main thumbnail for home/index pages. You can upload an image by clicking the &quot;upload image&quot; button next to each field. Once you upload the image, copy and past the URL to the image into the field.</p> 
  <p>You can also define a separate thumbnail image for Featured Articles to be displayed on the homepage slider. You will see a separate thumbnail field within in ET Settings box for featured thumbnails. The best size to use for these thumbnails is 1400x501px.</p> 
  <p><span class="style1">Important Note: You <u>must</u> CHMOD the &quot;cache&quot; folder located in the eStore directory to 777 for this script to work. You can CHMOD (change the permissions) of a file using your favorite FTP program. If you are confused try following <a href="http://www.siteground.com/tutorials/ftp/ftp_chmod.htm"><u>this tutorial</u></a><u>.</u> Of course instead of CHMODing the template folder (as in the tutorial) you would CHMOD the &quot;cache&quot; folder found within your theme's directory. </span></p> 
</div> 
<span class="boldtext">3. How do I add my title/logo? </span> 
<div class="indent">In this theme the title/logo is an image, which means you will need an image editor to add your own text. You can do this by opening the blank logo image located at Photoshop Files/logo_blank.png, or by opening the logo PSD file located at Photoshop Files/logo.psd. Replace the edited logo with the old logo by placing it in the following directory: theme/eStore/images, and naming the file "logo.png". If you need more room, or would like to edit the logo further, you can always do so by opening the original fully layered PSD file located at Photoshop Files/eStore.psd. You will also notice that there are different logos for each color scheme. If you are using one of the alternate colorschemes (Blue, Purple or Green) you will need to replace the associated logo images. These are located in the images/green, images/purple and images/blue folders.</div> 
 
<span class="boldtext">4. How do I manage advertisements on my blog? </span> 
<div class="indent">You can change the images used in each of the advertisements, as well as which URL each ad points to, through the custom option pages found in wp-admin. Once logged in to the wordpress admin panel, click &quot;Design&quot; and then &quot;eStore Theme Options&quot; to reveal the various theme options. You can also use the 125x125 advertisement widget by adding the ET: Advertisement widget to your sidebar, and filling in the required fields.  </div> 
 
  <span class="boldtext">5. How do I set up the featured slider on the homepage? </span> 
  <div class="indent"> 
  <p>The featured slider can be set up using two different methods. You can either populate the tabs using Pages, or you can populate it using posts from a designated category. In the Appearances > eStore Theme Options page in wp-admin, under the General Settings > Featured Slider tab, you will see an option that says "Use Pages." If you select this option then pages will be used, if you don't then posts will be used. If you want to use Pages then you simply select "Use Pages," and then below the option select which pages you would like to display in the slider. If you don't use pages, then simply select the "Featured Category" from the dropdown menu and posts from that category will be added to the slider. 
</p> 
</div> 
 
  <span class="boldtext">6. How do I set up the "deals of the day" slider on the homepage? </span> 
  <div class="indent"> 
  <p>These posts are pulled from a specific category that you define within the Appearances &gt; eStore Theme Options. Under the General Settings &gt; Homepage tab, you will see a dropdown menu where you can choose which category to use for your daily deals. You will also see a field where you can choose how many items to add to the slider. It's best to choose increments of 4, as 4 slides are displayed at a time with each cycle of the slider. </p></div> 
  
  <span class="boldtext">7. How do I set a price for each product? </span> 
  <div class="indent"> 
  <p>When you a write a post, you will notice a set of options below the text editor labeled ET Settings. Within this box will be a field for your product's price. You can also change the currency sign used from within the Appearances > eStore Theme Options page. </p></div> 
  
  <span class="boldtext">8. How do I integrate a shopping cart with eStore? </span> 
  <div class="indent"> 
  <p>eStore it self does not include any ecommerce functionality. Instead, we have made an effort to make our theme compatible with some already-existing and widely-used plugins. In not building the theme around a specific ecommerce platform, it also becomes much easier for the theme to be used with a wide array of plugins. That being said, we have pre-integrated two plugins, either of which will be the easiest to use.</p> 
  <p>1. <a href="http://wordpress.org/extend/plugins/wordpress-simple-paypal-shopping-cart/">Simple PayPal Shopping Cart</a> - This plugin is refreshing in its simplicity, but also lacks certain features found in other plugins. If you are looking for a really easy way to get your store off the ground, this is probably the plugin for you. The plugin will automatically use the price settings defined with each post from within the ET Settings, and the &quot;ADD TO CART&quot; button on each post page will work automatically as well. All you have to do is configure the plugin's main settings and you are good to go. </p> 
  <p>2. <a href="http://wordpress.org/extend/plugins/eshop/">eShop</a> - This plugin offers more functionality, but also requires more configuration to set up. After enabling the plugin, you will see a new set of options (labled &quot;Product Entry&quot;) added to each post under the text editor. You will need to fill out this information for each post, and then check the &quot;stock available&quot; option. After you have input the product information, you will notice that clicking the &quot;Add Cart&quot; button will reveal the product's add to cart feature. You will also need to configure the main eShop plugin settings, which are well documented within the eShop page in wp-admin. </p> 
  </div> 